# -*- coding: utf-8 -*-
"""BI_TP3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmrDDsHW5hhdw2gWzAlrxNT81fwqkLCB
"""

import kagglehub
from kagglehub import KaggleDatasetAdapter
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "faresashraf1001/supermarket-sales",
    "SuperMarket Analysis.csv",
)


# 1. Initial analysis
print(df.shape)
df.info()
print(df.describe())
print(df.isnull().sum())
print(df.isnull().values.any())

# 2. KPIs
ca_total = df["gross income"].sum()
profit_total = df["gross income"].sum()
nb_ventes = df.shape[0]
panier_moyen = df["gross income"].mean()

print(f"CA total      : {ca_total:.2f}")
print(f"Profit total  : {profit_total:.2f}")
print(f"Nb ventes     : {nb_ventes}")
print(f"Panier moyen  : {panier_moyen:.2f}")

# 3. K-Means
X = df[["gross income", "Quantity", "Rating"]]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42)
df["Cluster"] = kmeans.fit_predict(X_scaled)

# 3.4 Plot
plt.figure()
plt.scatter(
    df["gross income"], df["Quantity"], c=df["Cluster"], cmap="viridis", alpha=0.6
)
plt.xlabel("Total")
plt.ylabel("Quantity")
plt.title("Segmentation Clients")
plt.show()
